apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls
  namespace: homepage
spec:
  secretName: homepage-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: home.julianzanetti-lab.com
  dnsNames:
    - home.julianzanetti-lab.com
  duration: 2160h # 90d
  renewBefore: 360h # 15d