apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-widgets
  namespace: homepage
data:
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /
    - datetime:
        format: "dddd, DD MMMM YYYY HH:mm:ss"
    - kubernetes:
        cluster:
          show: true
        nodes:
          show: true
