apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - containerPort: 3000
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "home.julianzanetti-lab.com"
          volumeMounts:
            - name: settings
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
            - name: services
              mountPath: /app/config/services.yaml
              subPath: services.yaml
            - name: bookmarks
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
            - name: widgets
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: settings
          configMap:
            name: homepage-settings
        - name: services
          configMap:
            name: homepage-services
        - name: bookmarks
          configMap:
            name: homepage-bookmarks
        - name: widgets
          configMap:
            name: homepage-widgets
        - name: logs
          emptyDir: {}
