apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: grafana
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: grafana.julianzanetti-lab.com
  dnsNames:
    - grafana.julianzanetti-lab.com
  duration: 2160h # 90d
  renewBefore: 360h # 15d