loki:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
    storageClass: gp3
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 60
    timeoutSeconds: 10
    failureThreshold: 10
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 120
    timeoutSeconds: 10
    failureThreshold: 10

promtail:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 256Mi

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin123
  persistence:
    enabled: true
    size: 5Gi
    storageClass: gp3
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 384Mi
  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true
      label: grafana_dashboard
  image:
    tag: 12.1.0
