apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy-pedingtask
  namespace: pendingtask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-pedingtask
  template:
    metadata:
      labels:
        app: web-pedingtask
    spec:
      containers:
      - name: web-pedingtask
        image: julianzanetti/pending-task:1.0
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: db-pendingtask
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pendingtask-secret
              key: POSTGRES_DB
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pendingtask-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pendingtask-secret
              key: POSTGRES_PASSWORD