apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pendingtask-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: pendingtask.julianzanetti-lab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-svc-pedingtask
                port:
                  number: 8000