apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: prometheus
spec:
  secretName: prometheus-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: prometheus.julianzanetti-lab.com
  dnsNames:
    - prometheus.julianzanetti-lab.com
  duration: 2160h # 90d
  renewBefore: 360h # 15d