alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 384Mi
  persistentVolume:
    enabled: true
    size: 5Gi
    storageClass: "local-path"
  retention: 7d

# Activar exporters ligeros
nodeExporter:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

kubeStateMetrics:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi