apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: julianzanetti99@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-account-key
    solvers:
    - dns01:
        route53:
          region: sa-east-1
          accessKeyIDSecretRef:
            name: route53-credentials-secret
            key: aws_access_key_id
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: aws_secret_access_key